"""imagenes logo brand

Revision ID: 8f3def2ccbe8
Revises: 678bcb4336b6
Create Date: 2025-11-16 16:48:11.995842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f3def2ccbe8'
down_revision: Union[str, None] = '678bcb4336b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vehicle_images_id', table_name='vehicle_images')
    op.drop_table('vehicle_images')
    op.drop_index('ix_vehicles_id', table_name='vehicles')
    op.drop_index('ix_vehicles_nombre', table_name='vehicles')
    op.drop_index('ix_vehicles_referencia', table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index('ix_brands_id', table_name='brands')
    op.drop_index('ix_brands_name', table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('brands_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('logo_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='brands_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_brands_name', 'brands', ['name'], unique=False)
    op.create_index('ix_brands_id', 'brands', ['id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('vehicles_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('referencia', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('precio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('tipo', postgresql.ENUM('E_BIKE', 'E_MOPED', 'SCOOTER', 'E_SCOOTER', 'BIKE', name='vehicletype'), autoincrement=False, nullable=False),
    sa.Column('marca_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['marca_id'], ['brands.id'], name='vehicles_marca_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='vehicles_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_vehicles_referencia', 'vehicles', ['referencia'], unique=False)
    op.create_index('ix_vehicles_nombre', 'vehicles', ['nombre'], unique=False)
    op.create_index('ix_vehicles_id', 'vehicles', ['id'], unique=False)
    op.create_table('vehicle_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name='vehicle_images_vehicle_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='vehicle_images_pkey')
    )
    op.create_index('ix_vehicle_images_id', 'vehicle_images', ['id'], unique=False)
    # ### end Alembic commands ###
